// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtYN2m1B8nfeuhc-iTvyyykRVHUuCgTKk',
    appId: '1:818888655920:web:3744f22ed597513830d9f5',
    messagingSenderId: '818888655920',
    projectId: 'homeldr',
    authDomain: 'homeldr.firebaseapp.com',
    databaseURL: 'https://homeldr-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'homeldr.firebasestorage.app',
    measurementId: 'G-957MKF537W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB05twXNalZpnu7FnI_PigTUGAC8NNRRi0',
    appId: '1:818888655920:android:8ae1db323a4b948430d9f5',
    messagingSenderId: '818888655920',
    projectId: 'homeldr',
    databaseURL: 'https://homeldr-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'homeldr.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR2uXQJcCIMUwO5U3bP0GIGHZfHsxeBnw',
    appId: '1:818888655920:ios:0fd3b2996e21b1dd30d9f5',
    messagingSenderId: '818888655920',
    projectId: 'homeldr',
    databaseURL: 'https://homeldr-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'homeldr.firebasestorage.app',
    iosBundleId: 'com.example.appLdr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAR2uXQJcCIMUwO5U3bP0GIGHZfHsxeBnw',
    appId: '1:818888655920:ios:0fd3b2996e21b1dd30d9f5',
    messagingSenderId: '818888655920',
    projectId: 'homeldr',
    databaseURL: 'https://homeldr-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'homeldr.firebasestorage.app',
    iosBundleId: 'com.example.appLdr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtYN2m1B8nfeuhc-iTvyyykRVHUuCgTKk',
    appId: '1:818888655920:web:4b46ce7b08d71c1130d9f5',
    messagingSenderId: '818888655920',
    projectId: 'homeldr',
    authDomain: 'homeldr.firebaseapp.com',
    databaseURL: 'https://homeldr-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'homeldr.firebasestorage.app',
    measurementId: 'G-DG5YKJ863L',
  );
}
